# Generated by Django 5.1.3 on 2025-04-03 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('share1', models.ImageField(blank=True, upload_to='shares/')),
                ('share2', models.ImageField(blank=True, upload_to='shares/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
